export const aboutContent = {
  hero: {
    eyebrow: "About Phil",
    index: "Profile / 01",
    title: "Engineer by craft. Builder by curiosity.",
    body: "I'm a full-stack software engineer who likes complicated systems, useful products, and the careful work of making one feel like the other.",
    experience: "8+ years",
    experienceDetail: "building production software for real users",
  },
  thesis: {
    eyebrow: "The through line",
    title: "I turn complexity into products people can understand and trust.",
    body: "My work has moved from high-stakes exchange platforms to an independent mobile product and after-hours client work. The scale changes; the responsibility does not. I trace decisions across data, business rules, interfaces, and the people who rely on them.",
    note: "The portfolio is part of that practice: systems thinking, product judgment, and visual craft working together instead of competing for attention.",
  },
  principles: [
    {
      index: "01",
      title: "Systems thinker",
      body: "I look for the relationships underneath a feature: where its rules live, what changes across contexts, and which decisions should become reusable foundations.",
    },
    {
      index: "02",
      title: "Full-stack builder",
      body: "I am comfortable following a requirement from interface behavior through APIs, data models, validation, real-time delivery, testing, and production support.",
    },
    {
      index: "03",
      title: "Product partner",
      body: "I work best when engineering is present early—helping clarify the problem, shape the requirement, and protect the user's experience through implementation.",
    },
    {
      index: "04",
      title: "Continuous learner",
      body: "Independent products and client work give me room to test new platforms, tools, and disciplines, then bring the useful lessons back to larger systems.",
    },
  ],
  career: {
    eyebrow: "Career progression",
    index: "March 2018 — present",
    title: "A frontend foundation that kept widening.",
    body: "The through line is cumulative: interface craft became team leadership, platform architecture, full-stack ownership, and an independent product practice. Everything belongs to one chronology; the blueprint entries mark work built concurrently after hours.",
    entries: [
      {
        index: "01",
        anchorId: "earthcam",
        projectId: "earthcam",
        kind: "full-time",
        context: "Full-time path",
        start: { dateTime: "2018-03", label: "March 2018" },
        end: { dateTime: "2019-12", label: "December 2019" },
        roles: "Front-End Developer → Lead Front-End Developer",
        body: "Built a foundation in live-media interfaces, then stepped into product planning, architecture, delegation, and mentorship for a five-person frontend team.",
      },
      {
        index: "02",
        anchorId: "memx",
        projectId: "memx",
        kind: "full-time",
        context: "Full-time path",
        start: { dateTime: "2019-12", label: "December 2019" },
        end: { dateTime: "2023-01", label: "January 2023" },
        roles: "Front-End Engineer",
        seriesLabel: "MEMX / position 1 of 2",
        body: "Joined at the beginning of the member portal, building its onboarding, connectivity, and exchange-configuration tools before establishing reusable UI patterns for market-specific behavior.",
      },
      {
        index: "03",
        anchorId: "memx-senior",
        projectId: "memx",
        kind: "full-time",
        context: "Full-time path / promoted",
        start: { dateTime: "2023-01", label: "January 2023" },
        end: { dateTime: "2026-08", label: "August 2026" },
        roles: "Senior Full Stack Engineer",
        seriesLabel: "MEMX / position 2 of 2",
        body: "Expanded into server and database work, production support, and end-to-end feature ownership across eight market implementations, including real-time WebSocket delivery.",
      },
      {
        index: "04",
        anchorId: "pixelverse-studios",
        projectId: "pixelverse-studios",
        kind: "after-hours",
        context: "Part-time / after hours",
        start: { dateTime: "2024-01", label: "January 2024" },
        end: null,
        roles: "Co-Founder & Full Stack Engineer",
        body: "Co-founded a part-time studio for helping local businesses while experimenting with client delivery, web platforms, analytics, and search-oriented systems.",
      },
      {
        index: "05",
        anchorId: "domani",
        projectId: "domani",
        kind: "after-hours",
        context: "Independent / after hours",
        start: { dateTime: "2025-12", label: "December 2025" },
        end: null,
        roles: "Creator & Full-Stack Engineer",
        body: "Turned a personal frustration with productivity tools into a production iOS and Android product, expanding the practice into mobile development and product operations.",
      },
    ],
  },
} as const;
