export const resumeContent = {
  title: "Full Stack Software Engineer",
  name: "Phil Arfuso",
  location: "Cliffside Park, NJ 07010",
  phone: "(201) 638-1769",
  phoneHref: "tel:+12016381769",
  email: "arfusop@gmail.com",
  linkedIn: "https://www.linkedin.com/in/phil-arfuso",
  linkedInLabel: "linkedin.com/in/phil-arfuso",
  github: "https://github.com/parfuso-pvs",
  githubLabel: "github.com/parfuso-pvs",
  profile:
    "Full-stack software engineer with 8+ years of experience building production software across web and mobile. I turn complex business rules and data models into reliable systems that are easier to use and maintain. My work spans React, React Native, Node.js, databases, cloud infrastructure, legacy modernization, and technical leadership. I also co-founded a part-time digital agency focused on web, SEO, and analytics for service businesses.",
  technologies: [
    {
      label: "Languages & frameworks",
      items: [
        "JavaScript",
        "TypeScript",
        "React",
        "React Native",
        "Next.js",
        "Node.js",
        "Express",
        "GraphQL",
        "Apollo",
        "Remix",
      ],
    },
    {
      label: "Data & architecture",
      items: [
        "PostgreSQL",
        "MongoDB",
        "MySQL",
        "Prisma",
        "Supabase",
        "Firebase",
        "REST APIs",
        "Microservices",
        "WebSockets",
      ],
    },
    {
      label: "Infrastructure & quality",
      items: [
        "AWS",
        "Docker",
        "GitHub Actions",
        "Jenkins",
        "CI/CD",
        "Jest",
        "Playwright",
        "Cypress",
        "Sentry",
      ],
    },
    {
      label: "Frontend & practices",
      items: [
        "Tailwind CSS",
        "Styled Components",
        "SCSS",
        "Mantine",
        "Zustand",
        "Redux",
        "Storybook",
        "Accessibility",
        "System design",
      ],
    },
  ],
  experience: [
    {
      company: "MEMX",
      location: "New Jersey",
      tenure: "6 yrs 9 mos",
      roles: [
        {
          title: "Senior Full Stack Engineer",
          dates: "January 2023 to August 2026",
          bullets: [
            "Co-architected a database-driven platform supporting equities, options, crypto, and market technology clients across different regulatory environments.",
            "Built a shared UI platform that adapted data, rules, and validation by market while keeping one codebase.",
            "Designed server-side business logic and PostgreSQL data models built around integrity, traceability, and regulatory requirements.",
            "Built API and validation layers that kept backend services and administrative tools aligned around consistent data contracts.",
            "Led the modularization of shared UI components and service endpoints, reducing duplication and improving feature rollout time by 35%.",
            "Delivered real-time trading and administrative features using WebSocket event streams.",
            "Maintained CI/CD pipelines and automated testing that supported reliable deployments and compliance audits.",
          ],
        },
        {
          title: "Front-End Engineer",
          dates: "December 2019 to December 2022",
          bullets: [
            "Helped build MEMX's core React application from the ground up and maintained it through major feature expansions.",
            "Established the component architecture that supported the application as it grew.",
            "Improved real-time market-data rendering through memoization, virtualization, and incremental updates.",
            "Set frontend standards for code quality, accessibility, and type safety.",
            "Worked with backend teams to improve API design, data efficiency, and the connection between user workflows and system rules.",
            "Introduced Jest and Playwright testing to strengthen regression coverage and release confidence.",
          ],
        },
      ],
    },
    {
      company: "EarthCam, Inc.",
      location: "New Jersey",
      tenure: "1 yr 10 mos",
      roles: [
        {
          title: "Lead Front-End Developer",
          dates: "July 2019 to December 2019",
          bullets: [
            "Led and mentored five junior front-end developers while managing planning, reviews, and delivery across concurrent applications.",
            "Maintained stability and delivered client features for a legacy jQuery platform while coordinating phased modernization.",
            "Enhanced media playback, real-time feed rendering, and UI performance for the React-based EarthCam Public Player.",
            "Collaborated with product and media teams to architect and launch EarthCam TV as a streaming-style interface for programmable public-camera channels.",
            "Designed and maintained a Storybook component library with 50+ reusable UI elements, improving feature delivery speed by over 40%.",
            "Migrated an internal Angular tool to React, reducing technical debt and improving performance and maintainability.",
            "Established version control, CI/CD, and frontend quality standards across projects.",
            "Served as the primary product, design, and engineering liaison for client and operational requirements.",
          ],
        },
        {
          title: "Front-End Developer",
          dates: "March 2018 to July 2019",
          bullets: [
            "Maintained and refactored a large legacy jQuery platform, improving stability, load performance, and code organization.",
            "Built a React Share component and integrated it into the legacy application as a standalone bundle.",
            "Built and maintained a React application for internal and external users viewing live and recorded construction-site and public-landmark camera feeds.",
            "Developed media capabilities including real-time video playback, filtered clip generation, timelapses, and high-resolution image archives.",
            "Implemented Sentry error tracking, improving front-end observability and production issue resolution.",
            "Collaborated with backend and video teams to optimize data streaming, asset retrieval, and high-traffic media experiences.",
          ],
        },
      ],
    },
  ],
  ventures: [
    {
      company: "Domani",
      location: "Production iOS & Android application",
      title: "Co-Founder & Sole Developer",
      dates: "December 2025 to Present",
      bullets: [
        "Co-founded and solely developed Domani, an evening-planning and daily-priority application launched to production on iOS and Android in May 2026.",
        "Built the cross-platform mobile application with React Native, JavaScript, Tailwind CSS, Supabase, and SQL, alongside its live web presence.",
        "Delivered planning features including a top daily priority, task categories, reminders, intentional task rollover, and cross-platform lifetime-access purchasing.",
        "Own end-to-end development, production maintenance, and ongoing feature delivery across both mobile platforms.",
      ],
    },
    {
      company: "Independent Digital Agency",
      location: "Part-time",
      title: "Co-Founder & Full Stack Engineer",
      dates: "January 2024 to Present",
      bullets: [
        "Co-founded and operate a small digital agency serving small and midsize service businesses outside my full-time role.",
        "Lead technical architecture for platforms built with Next.js, TypeScript, Supabase, and Tailwind CSS.",
        "Built a reusable React and Vite component library distributed through private npm packages.",
        "Built deployment and hosting pipelines across Netlify, Fly.io, and DigitalOcean.",
        "Connected Google Search Console, GA4, Plausible, and SiteBehavior to support practical SEO reporting and decisions.",
        "Built content systems for service-area pages, article hubs, and local search landing pages.",
        "Led technical delivery from discovery through launch alongside design and marketing partners.",
        "Client results included 40% faster page loads and reported organic visibility gains of 25% to 50%.",
      ],
    },
  ],
} as const;
