export const resumeContent = {
  title: "Full Stack Software Engineer",
  name: "Phil Arfuso",
  location: "Cliffside Park, NJ 07010",
  phone: "(201) 638-1769",
  phoneHref: "tel:+12016381769",
  email: "arfusop@gmail.com",
  linkedIn: "https://www.linkedin.com/in/phil-arfuso",
  linkedInLabel: "linkedin.com/in/phil-arfuso",
  github: "https://github.com/parfuso-pvs",
  githubLabel: "github.com/parfuso-pvs",
  profile:
    "Full Stack Software Engineer with 8+ years of experience architecting, developing, and optimizing data-driven web applications. Builds maintainable systems spanning complex business logic, multi-market data models, real-time interfaces, and cloud infrastructure. Experienced in technical leadership, legacy modernization, reusable platform design, and cross-functional product delivery across React, React Native, Node.js, and cloud infrastructure. Also co-founded a part-time digital agency delivering modern web, SEO, and analytics solutions for service businesses.",
  technologies: [
    {
      label: "Languages & frameworks",
      items: [
        "JavaScript",
        "TypeScript",
        "React",
        "React Native",
        "Next.js",
        "Node.js",
        "Express",
        "GraphQL",
        "Apollo",
        "Remix",
      ],
    },
    {
      label: "Data & architecture",
      items: [
        "PostgreSQL",
        "MongoDB",
        "MySQL",
        "Prisma",
        "Supabase",
        "Firebase",
        "REST APIs",
        "Microservices",
        "WebSockets",
      ],
    },
    {
      label: "Infrastructure & quality",
      items: [
        "AWS",
        "Docker",
        "GitHub Actions",
        "Jenkins",
        "CI/CD",
        "Jest",
        "Playwright",
        "Cypress",
        "Sentry",
      ],
    },
    {
      label: "Frontend & practices",
      items: [
        "Tailwind CSS",
        "Styled Components",
        "SCSS",
        "Mantine",
        "Zustand",
        "Redux",
        "Storybook",
        "Accessibility",
        "System design",
      ],
    },
  ],
  experience: [
    {
      company: "MEMX",
      location: "New Jersey",
      roles: [
        {
          title: "Senior Full Stack Engineer",
          dates: "January 2023 - Present",
          bullets: [
            "Co-architected a database-driven ecosystem supporting Equities, Options, Crypto, and external Market Technology clients across distinct regulatory environments.",
            "Engineered a shared UI platform that adapts datasets, rules, and form validations by market while retaining one codebase.",
            "Designed server-side business logic and PostgreSQL/Prisma schemas supporting compliance, data integrity, and operational traceability.",
            "Implemented API orchestration and data-validation layers that enforce contracts between backend microservices and frontend administrative tools.",
            "Led modularization of cross-market UI components and service endpoints, reducing duplication and improving feature rollout time by 35%.",
            "Delivered WebSocket-based trading and administrative features through low-latency event streams.",
            "Oversaw CI/CD pipelines and testing frameworks supporting deployment consistency and compliance audits.",
          ],
        },
        {
          title: "Front-End Engineer",
          dates: "December 2019 - December 2022",
          bullets: [
            "Served as founding engineer for MEMX's core React application, architecting it from the ground up and maintaining it through major feature expansions.",
            "Established a reusable component architecture that became the foundation for subsequent UI development.",
            "Improved real-time market-data rendering through memoization, virtualization, and incremental updates.",
            "Enforced coding standards, accessibility compliance, and type safety across the growing codebase.",
            "Collaborated with backend teams to refine API design, improve data efficiency, and align client workflows with system-level business logic.",
            "Introduced Jest and Playwright automated testing, improving regression coverage and deployment confidence.",
          ],
        },
      ],
    },
    {
      company: "EarthCam, Inc.",
      location: "New Jersey",
      roles: [
        {
          title: "Lead Front-End Developer",
          dates: "July 2019 - December 2019",
          bullets: [
            "Led and mentored five junior front-end developers while managing planning, reviews, and delivery across concurrent applications.",
            "Maintained stability and delivered client features for a legacy jQuery platform while coordinating phased modernization.",
            "Enhanced media playback, real-time feed rendering, and UI performance for the React-based EarthCam Public Player.",
            "Collaborated with product and media teams to architect and launch EarthCam TV as a streaming-style interface for programmable public-camera channels.",
            "Designed and maintained a Storybook component library with 50+ reusable UI elements, improving feature delivery speed by over 40%.",
            "Migrated an internal Angular tool to React, reducing technical debt and improving performance and maintainability.",
            "Championed version-control, CI/CD, and front-end quality standards across projects.",
            "Served as the primary product, design, and engineering liaison for client and operational requirements.",
          ],
        },
        {
          title: "Front-End Developer",
          dates: "March 2018 - July 2019",
          bullets: [
            "Maintained and refactored a large legacy jQuery platform, improving stability, load performance, and code organization.",
            "Built a React Share component and integrated it into the legacy application as a standalone bundle.",
            "Built and maintained a React application for internal and external users viewing live and recorded construction-site and public-landmark camera feeds.",
            "Developed media capabilities including real-time video playback, filtered clip generation, timelapses, and high-resolution image archives.",
            "Implemented Sentry error tracking, improving front-end observability and production issue resolution.",
            "Collaborated with backend and video teams to optimize data streaming, asset retrieval, and high-traffic media experiences.",
          ],
        },
      ],
    },
  ],
  ventures: [
    {
      company: "Domani",
      location: "Production iOS & Android application",
      title: "Co-Founder & Sole Developer",
      dates: "December 2025 - Present",
      bullets: [
        "Co-founded and solely developed Domani, an evening-planning and daily-priority application launched to production on iOS and Android in May 2026.",
        "Built the cross-platform mobile application with React Native, JavaScript, Tailwind CSS, Supabase, and SQL, alongside its live web presence.",
        "Delivered planning features including a top daily priority, task categories, reminders, intentional task rollover, and cross-platform lifetime-access purchasing.",
        "Owns end-to-end development, production maintenance, and consistent incremental feature delivery across both mobile platforms.",
      ],
    },
    {
      company: "Independent Digital Agency",
      location: "Part-time",
      title: "Co-Founder & Full Stack Engineer",
      dates: "January 2024 - Present",
      bullets: [
        "Co-founded and operates a boutique digital agency serving small-to-midsize service businesses outside full-time work hours.",
        "Acts as sole technical architect, building platforms with Next.js 14, TypeScript, Supabase, and Tailwind CSS.",
        "Created a reusable React/Vite component library distributed through private npm packages.",
        "Built deployment and hosting pipelines across Netlify, Fly.io, and DigitalOcean.",
        "Integrated Google Search Console, GA4, Plausible, and SiteBehavior into data-driven SEO systems.",
        "Implemented metadata-driven content architecture for service-area pages, blog hubs, and local SEO landing pages.",
        "Managed technical delivery from discovery through launch with design and marketing partners.",
        "Delivered reported results including 40% faster page loads and 25-50% gains in organic visibility.",
      ],
    },
  ],
} as const;
